name: my-pipeline
jobs:
  - name: install
    image: oven/bun:1.3.7
    steps:
      - action: checkout
      - run: ["bun", "install"]
  - name: build
    image: oven/bun:1.3.7
    steps:
      - action: checkout
      - run: ["bun", "run", "build"]
    dependsOn:
      - "install"
  - name: test
    image: oven/bun:1.3.7
    steps:
      - action: checkout
      - run: ["bun", "test"]
    dependsOn:
      - "install"
